# name:  服务端self-hosted runner编译

# on:
#     push:
#         branches:
#             - main

# jobs:
#     build:
#         # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
#         runs-on: self-hosted
#         steps:
#             # 获取源码
#             - name: 迁出代码
#               # 使用action库  actions/checkout获取源码
#               uses: actions/checkout@master

#             # 安装依赖
#             - name: 安装依赖
#               run: yarn install

#             # 打包
#             - name: 打包
#               run: yarn run build
